#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Shuhei Yanaighori shuheidaigaku22@gmail.com
# SPDX-License-Identifier: BSB-3-Clause
import sys
ans = 0
mul = 1
for line in sys.stdin:
    try:
        num = int(line)
    except:
        num = float(line)
    mul *= num
    ans += num

print(mul, ans)

